### ISSUE TITLE
Missing dot on last item in bind file.

### ISSUE THREAD

**Issue by pcorliss** [barnybug/cli53#113] opened 2015-10-14 15:32 UTC
When backing up and then restoring the last item in our bind file was a CNAME to another internal resource. The resource didn't end with a `.` created a record like `foo CNAME bar.example.com.example.com.`

```
./cli53-linux-amd64 export example.com > example.com.bind.bkp
./cli53-linux-amd64 import --file example.com.bind.bkp --replace example.com
```

**Comment by barnybug** [comment] 2015-10-14 15:37
I couldn't reproduce this, would it be possible to attach a reproduction case?

**Comment by barnybug** [comment] 2015-10-20 07:43
Hi, any update?

**Comment by barnybug** [comment] 2015-10-21 12:59
Closing.

**Closed by barnybug** 2015-10-21 12:59 UTC

**Comment by arturmartins** [comment] 2016-05-30 18:06
I think I had the same issue last week. Some of my DNS records in AWS Route53 did not have the ending dot (example: CNAME server1.example.com)

Therefore, when I export the domain `example.com`, the CNAME was been exported as `server1.example.com`  instead of `server1` (without the domain) or `server1.storyful.com.` (adding the dot at the end).

The way I fixed was to add the ending dot to every DNS record in AWS Route53.

Since adding the dot is not enforced by AWS, cli53 should probably add some intelligence to strip the domain or add the ending dot for DNS records that match the domain at the end. That does not solve the issue of CNAME mail.example.com > mail.google.com being imported as mail.google.com.example.com due lack of ending dot.
